// Purpose: Scene-level global controls shared by character shaders.
#ifndef CHARA_GLOBALS_V2_INCLUDED
#define CHARA_GLOBALS_V2_INCLUDED

float3 _GlobalCharacterRenderLightDirection;
float4 _GlobalCharacterRenderLightColor;
float _GlobalCharacterRenderLightStrength;
float _GlobalCharacterRenderLightToggle;
float _GlobalCharacterRenderLightFollowCameraXZ;
float _GlobalCharacterRenderBackLightToggle;
float3 _GlobalCharacterRenderVirtualLightCameraDirection;
float3 _GlobalCharacterRenderVirtualLightMaskCameraDirection;
float4 _GlobalCharacterRenderVirtualLightColor;
float _GlobalCharacterRenderVirtualLightIntensity;
float _GlobalCharacterRenderVirtualLightOffset;
float _GlobalCharacterAdditionalLightsEnabled;
float _GlobalCharacterAdditionalLightsDiffuseEnabled;
float _GlobalCharacterAdditionalLightsSpecularEnabled;
float _GlobalCharacterRenderPlanarShadowToggle;
float _GlobalCharacterRenderPlanarShadowDirectionMode;
float3 _GlobalCharacterRenderPlanarShadowDirection;
float _GlobalCharacterRenderPlanarShadowStrength;
float _GlobalCharacterRenderPlanarShadowParametersOverride;
float _GlobalCharacterRenderPlanarShadowFalloff;
float _GlobalCharacterRenderPlanarShadowRange;
float _GlobalCharacterRenderPlanarShadowPlaneHeight;
float3 _GlobalCharacterRenderPlanarShadowGlobalCenter;
float4 _GlobalCharacterRenderPlanarShadowColor;
float _GlobalCharacterRenderOutlineToggle;
float _GlobalCharacterRenderSceneShadowModeOverride;
float _GlobalCharacterRenderSceneShadowMode;
float _GlobalCharacterRenderSpecularShadowStrengthOverride;
float _GlobalCharacterRenderSpecularShadowStrength;
float _GlobalCharacterRenderRimLightToggle;
float _GlobalCharacterRenderRimCustomDirectionEnabled;
float _GlobalCharacterRenderRimDirectionSpace;
float3 _GlobalCharacterRenderRimDirection;
float _GlobalCharacterRenderRimFakePointMaskEnabled;
float3 _GlobalCharacterRenderRimFakePointMaskPosition;
float _GlobalCharacterRenderRimFakePointMaskRange;
float _GlobalCharacterRenderRimFakePointMaskPower;
float _GlobalCharacterRenderRimFakeDirectMaskEnabled;
float3 _GlobalCharacterRenderRimFakeDirectMaskDirection;
float3 _GlobalCharacterRenderRimFakeDirectMaskPosition;
float _GlobalCharacterRenderRimFakeDirectMaskRange;
float _GlobalCharacterRenderRimIntensity;
float _GlobalCharacterRenderFinalColorGradientToggle;
float _GlobalCharacterRenderFinalColorGradientParametersOverride;
float4 _GlobalCharacterRenderFinalColorGradientColor;
float _GlobalCharacterRenderFinalColorGradientMinY;
float _GlobalCharacterRenderFinalColorGradientMaxY;
half _GlobalIndirecIntensity;
half3 _GlobalIndirectTintColor;
// 开启时将场景 SH 采样替换为白色，再由全局间接漫反射颜色统一着色。
half _GlobalCharacterRenderOverrideSceneAmbient;
float _CustomMainLightPerObjectShadowDirectionEnabled;
float3 _CustomMainLightPerObjectShadowDirection;

float3 _GlobalMonsterRenderLightDirection;
float4 _GlobalMonsterRenderLightColor;
float _GlobalMonsterRenderLightStrength;
float _GlobalMonsterRenderLightToggle;
float _GlobalMonsterRenderLightFollowCameraXZ;
float _GlobalMonsterAdditionalLightsEnabled;
float _GlobalMonsterAdditionalLightsDiffuseEnabled;
float _GlobalMonsterAdditionalLightsSpecularEnabled;
float _GlobalMonsterRenderOverrideSceneAmbient;
float _GlobalMonsterIndirectIntensity;
float3 _GlobalMonsterIndirectTintColor;
float _GlobalMonsterRenderOutlineToggle;
float _GlobalMonsterRenderRimLightToggle;
float _GlobalMonsterRenderFinalColorGradientToggle;
float _GlobalMonsterRenderFinalColorGradientParametersOverride;
float4 _GlobalMonsterRenderFinalColorGradientColor;
float _GlobalMonsterRenderFinalColorGradientMinY;
float _GlobalMonsterRenderFinalColorGradientMaxY;
// Gun V2 global controls use a separate namespace from character and monster materials.
float3 _GlobalGunRenderLightDirection;
float4 _GlobalGunRenderLightColor;
float _GlobalGunRenderLightStrength;
float _GlobalGunRenderLightToggle;
float _GlobalGunRenderLightFollowCameraXZ;
float _GlobalGunAdditionalLightsEnabled;
float _GlobalGunAdditionalLightsDiffuseEnabled;
float _GlobalGunAdditionalLightsSpecularEnabled;
float _GlobalGunRenderOverrideSceneAmbient;
float _GlobalGunIndirectIntensity;
float3 _GlobalGunIndirectTintColor;
float _GlobalGunRenderOutlineToggle;
float _GlobalGunRenderRimLightToggle;
float _GlobalGunRenderFinalColorGradientToggle;
float _GlobalGunRenderFinalColorGradientParametersOverride;
float4 _GlobalGunRenderFinalColorGradientColor;
float _GlobalGunRenderFinalColorGradientMinY;
float _GlobalGunRenderFinalColorGradientMaxY;

// Timeline character override values are supplied through MaterialPropertyBlock.
// A zero weight deliberately keeps the existing scene-global path byte-for-byte
// compatible; this lets a Timeline bind a character root without changing its
// prefab or instancing any material.
float _CharacterRenderTimelineMainLightWeight;
float3 _CharacterRenderTimelineMainLightDirection;
float4 _CharacterRenderTimelineMainLightColor;
float _CharacterRenderTimelineMainLightStrength;
float _CharacterRenderTimelineMainLightToggle;
float _CharacterRenderTimelineMainLightFollowCameraXZ;
float _CharacterRenderTimelineBackLightToggle;
float _CharacterRenderTimelineVirtualLightWeight;
float3 _CharacterRenderTimelineVirtualLightCameraDirection;
float3 _CharacterRenderTimelineVirtualLightMaskCameraDirection;
float4 _CharacterRenderTimelineVirtualLightColor;
float _CharacterRenderTimelineVirtualLightIntensity;
float _CharacterRenderTimelineVirtualLightOffset;
float _CharacterRenderTimelineAdditionalLightsWeight;
float _CharacterRenderTimelineAdditionalLightsEnabled;
float _CharacterRenderTimelineAdditionalLightsDiffuseEnabled;
float _CharacterRenderTimelineAdditionalLightsSpecularEnabled;
float _CharacterRenderTimelinePlanarShadowWeight;
float _CharacterRenderTimelinePlanarShadowToggle;
float _CharacterRenderTimelinePlanarShadowDirectionMode;
float3 _CharacterRenderTimelinePlanarShadowDirection;
float _CharacterRenderTimelinePlanarShadowStrength;
float _CharacterRenderTimelinePlanarShadowParametersOverride;
float _CharacterRenderTimelinePlanarShadowFalloff;
float _CharacterRenderTimelinePlanarShadowRange;
float _CharacterRenderTimelinePlanarShadowPlaneHeight;
float3 _CharacterRenderTimelinePlanarShadowGlobalCenter;
float4 _CharacterRenderTimelinePlanarShadowColor;
float _CharacterRenderTimelineOutlineWeight;
float _CharacterRenderTimelineOutlineToggle;
float _CharacterRenderTimelineSceneShadowWeight;
float _CharacterRenderTimelineSceneShadowModeOverride;
float _CharacterRenderTimelineSceneShadowMode;
float _CharacterRenderTimelineHighQualityShadowStrengthWeight;
float _CharacterRenderTimelinePerObjectShadowStrength;
float _CharacterRenderTimelineSpecularShadowStrength;
float _CharacterRenderTimelineRimLightWeight;
float _CharacterRenderTimelineRimLightToggle;
float _CharacterRenderTimelineFinalGradientWeight;
float _CharacterRenderTimelineFinalGradientToggle;
float _CharacterRenderTimelineFinalGradientParametersOverride;
float4 _CharacterRenderTimelineFinalGradientColor;
float _CharacterRenderTimelineFinalGradientMinY;
float _CharacterRenderTimelineFinalGradientMaxY;
float _CharacterRenderTimelineIndirectLightWeight;
float _CharacterRenderTimelineOverrideSceneAmbient;
float _CharacterRenderTimelineIndirectIntensity;
float3 _CharacterRenderTimelineIndirectTintColor;

float CharaTimelineOverrideFloat(float sceneValue, float timelineValue, float weight)
{
    return lerp(sceneValue, timelineValue, saturate(weight));
}

float3 CharaTimelineOverrideFloat3(float3 sceneValue, float3 timelineValue, float weight)
{
    return lerp(sceneValue, timelineValue, saturate(weight));
}

float4 CharaTimelineOverrideFloat4(float4 sceneValue, float4 timelineValue, float weight)
{
    return lerp(sceneValue, timelineValue, saturate(weight));
}

half CharaResolveSpecularShadowStrength(half materialStrength)
{
    half timelineWeight = saturate((half)_CharacterRenderTimelineHighQualityShadowStrengthWeight);
    half sceneStrength = lerp(
        1.0h,
        saturate((half)_GlobalCharacterRenderSpecularShadowStrength),
        saturate((half)_GlobalCharacterRenderSpecularShadowStrengthOverride));
    half resolvedStrength = lerp(
        sceneStrength,
        saturate((half)_CharacterRenderTimelineSpecularShadowStrength),
        timelineWeight);
    return saturate(materialStrength) * resolvedStrength;
}

// Keep call sites readable: all existing Chara_V2 consumers continue to read
// their scene-global identifiers, while Timeline-bound renderers resolve the
// matching local MaterialPropertyBlock value first.
#define _GlobalCharacterRenderLightDirection CharaTimelineOverrideFloat3(_GlobalCharacterRenderLightDirection, _CharacterRenderTimelineMainLightDirection, _CharacterRenderTimelineMainLightWeight)
#define _GlobalCharacterRenderLightColor CharaTimelineOverrideFloat4(_GlobalCharacterRenderLightColor, _CharacterRenderTimelineMainLightColor, _CharacterRenderTimelineMainLightWeight)
#define _GlobalCharacterRenderLightStrength CharaTimelineOverrideFloat(_GlobalCharacterRenderLightStrength, _CharacterRenderTimelineMainLightStrength, _CharacterRenderTimelineMainLightWeight)
#define _GlobalCharacterRenderLightToggle CharaTimelineOverrideFloat(_GlobalCharacterRenderLightToggle, _CharacterRenderTimelineMainLightToggle, _CharacterRenderTimelineMainLightWeight)
#define _GlobalCharacterRenderLightFollowCameraXZ CharaTimelineOverrideFloat(_GlobalCharacterRenderLightFollowCameraXZ, _CharacterRenderTimelineMainLightFollowCameraXZ, _CharacterRenderTimelineMainLightWeight)
#define _GlobalCharacterRenderBackLightToggle CharaTimelineOverrideFloat(_GlobalCharacterRenderBackLightToggle, _CharacterRenderTimelineBackLightToggle, _CharacterRenderTimelineMainLightWeight)
#define _GlobalCharacterRenderVirtualLightCameraDirection CharaTimelineOverrideFloat3(_GlobalCharacterRenderVirtualLightCameraDirection, _CharacterRenderTimelineVirtualLightCameraDirection, _CharacterRenderTimelineVirtualLightWeight)
#define _GlobalCharacterRenderVirtualLightMaskCameraDirection CharaTimelineOverrideFloat3(_GlobalCharacterRenderVirtualLightMaskCameraDirection, _CharacterRenderTimelineVirtualLightMaskCameraDirection, _CharacterRenderTimelineVirtualLightWeight)
#define _GlobalCharacterRenderVirtualLightColor CharaTimelineOverrideFloat4(_GlobalCharacterRenderVirtualLightColor, _CharacterRenderTimelineVirtualLightColor, _CharacterRenderTimelineVirtualLightWeight)
#define _GlobalCharacterRenderVirtualLightIntensity CharaTimelineOverrideFloat(_GlobalCharacterRenderVirtualLightIntensity, _CharacterRenderTimelineVirtualLightIntensity, _CharacterRenderTimelineVirtualLightWeight)
#define _GlobalCharacterRenderVirtualLightOffset CharaTimelineOverrideFloat(_GlobalCharacterRenderVirtualLightOffset, _CharacterRenderTimelineVirtualLightOffset, _CharacterRenderTimelineVirtualLightWeight)
#define _GlobalCharacterAdditionalLightsEnabled CharaTimelineOverrideFloat(_GlobalCharacterAdditionalLightsEnabled, _CharacterRenderTimelineAdditionalLightsEnabled, _CharacterRenderTimelineAdditionalLightsWeight)
#define _GlobalCharacterAdditionalLightsDiffuseEnabled CharaTimelineOverrideFloat(_GlobalCharacterAdditionalLightsDiffuseEnabled, _CharacterRenderTimelineAdditionalLightsDiffuseEnabled, _CharacterRenderTimelineAdditionalLightsWeight)
#define _GlobalCharacterAdditionalLightsSpecularEnabled CharaTimelineOverrideFloat(_GlobalCharacterAdditionalLightsSpecularEnabled, _CharacterRenderTimelineAdditionalLightsSpecularEnabled, _CharacterRenderTimelineAdditionalLightsWeight)
#define _GlobalCharacterRenderPlanarShadowToggle CharaTimelineOverrideFloat(_GlobalCharacterRenderPlanarShadowToggle, _CharacterRenderTimelinePlanarShadowToggle, _CharacterRenderTimelinePlanarShadowWeight)
#define _GlobalCharacterRenderPlanarShadowDirectionMode CharaTimelineOverrideFloat(_GlobalCharacterRenderPlanarShadowDirectionMode, _CharacterRenderTimelinePlanarShadowDirectionMode, _CharacterRenderTimelinePlanarShadowWeight)
#define _GlobalCharacterRenderPlanarShadowDirection CharaTimelineOverrideFloat3(_GlobalCharacterRenderPlanarShadowDirection, _CharacterRenderTimelinePlanarShadowDirection, _CharacterRenderTimelinePlanarShadowWeight)
#define _GlobalCharacterRenderPlanarShadowStrength CharaTimelineOverrideFloat(_GlobalCharacterRenderPlanarShadowStrength, _CharacterRenderTimelinePlanarShadowStrength, _CharacterRenderTimelinePlanarShadowWeight)
#define _GlobalCharacterRenderPlanarShadowParametersOverride CharaTimelineOverrideFloat(_GlobalCharacterRenderPlanarShadowParametersOverride, _CharacterRenderTimelinePlanarShadowParametersOverride, _CharacterRenderTimelinePlanarShadowWeight)
#define _GlobalCharacterRenderPlanarShadowFalloff CharaTimelineOverrideFloat(_GlobalCharacterRenderPlanarShadowFalloff, _CharacterRenderTimelinePlanarShadowFalloff, _CharacterRenderTimelinePlanarShadowWeight)
#define _GlobalCharacterRenderPlanarShadowRange CharaTimelineOverrideFloat(_GlobalCharacterRenderPlanarShadowRange, _CharacterRenderTimelinePlanarShadowRange, _CharacterRenderTimelinePlanarShadowWeight)
#define _GlobalCharacterRenderPlanarShadowPlaneHeight CharaTimelineOverrideFloat(_GlobalCharacterRenderPlanarShadowPlaneHeight, _CharacterRenderTimelinePlanarShadowPlaneHeight, _CharacterRenderTimelinePlanarShadowWeight)
#define _GlobalCharacterRenderPlanarShadowGlobalCenter CharaTimelineOverrideFloat3(_GlobalCharacterRenderPlanarShadowGlobalCenter, _CharacterRenderTimelinePlanarShadowGlobalCenter, _CharacterRenderTimelinePlanarShadowWeight)
#define _GlobalCharacterRenderPlanarShadowColor CharaTimelineOverrideFloat4(_GlobalCharacterRenderPlanarShadowColor, _CharacterRenderTimelinePlanarShadowColor, _CharacterRenderTimelinePlanarShadowWeight)
#define _GlobalCharacterRenderOutlineToggle CharaTimelineOverrideFloat(_GlobalCharacterRenderOutlineToggle, _CharacterRenderTimelineOutlineToggle, _CharacterRenderTimelineOutlineWeight)
#define _GlobalCharacterRenderSceneShadowModeOverride CharaTimelineOverrideFloat(_GlobalCharacterRenderSceneShadowModeOverride, _CharacterRenderTimelineSceneShadowModeOverride, _CharacterRenderTimelineSceneShadowWeight)
#define _GlobalCharacterRenderSceneShadowMode CharaTimelineOverrideFloat(_GlobalCharacterRenderSceneShadowMode, _CharacterRenderTimelineSceneShadowMode, _CharacterRenderTimelineSceneShadowWeight)
#define _GlobalCharacterRenderRimLightToggle CharaTimelineOverrideFloat(_GlobalCharacterRenderRimLightToggle, _CharacterRenderTimelineRimLightToggle, _CharacterRenderTimelineRimLightWeight)
#define _GlobalCharacterRenderFinalColorGradientToggle CharaTimelineOverrideFloat(_GlobalCharacterRenderFinalColorGradientToggle, _CharacterRenderTimelineFinalGradientToggle, _CharacterRenderTimelineFinalGradientWeight)
#define _GlobalCharacterRenderFinalColorGradientParametersOverride CharaTimelineOverrideFloat(_GlobalCharacterRenderFinalColorGradientParametersOverride, _CharacterRenderTimelineFinalGradientParametersOverride, _CharacterRenderTimelineFinalGradientWeight)
#define _GlobalCharacterRenderFinalColorGradientColor CharaTimelineOverrideFloat4(_GlobalCharacterRenderFinalColorGradientColor, _CharacterRenderTimelineFinalGradientColor, _CharacterRenderTimelineFinalGradientWeight)
#define _GlobalCharacterRenderFinalColorGradientMinY CharaTimelineOverrideFloat(_GlobalCharacterRenderFinalColorGradientMinY, _CharacterRenderTimelineFinalGradientMinY, _CharacterRenderTimelineFinalGradientWeight)
#define _GlobalCharacterRenderFinalColorGradientMaxY CharaTimelineOverrideFloat(_GlobalCharacterRenderFinalColorGradientMaxY, _CharacterRenderTimelineFinalGradientMaxY, _CharacterRenderTimelineFinalGradientWeight)
#define _GlobalCharacterRenderOverrideSceneAmbient CharaTimelineOverrideFloat(_GlobalCharacterRenderOverrideSceneAmbient, _CharacterRenderTimelineOverrideSceneAmbient, _CharacterRenderTimelineIndirectLightWeight)
#define _GlobalIndirecIntensity CharaTimelineOverrideFloat(_GlobalIndirecIntensity, _CharacterRenderTimelineIndirectIntensity, _CharacterRenderTimelineIndirectLightWeight)
#define _GlobalIndirectTintColor CharaTimelineOverrideFloat3(_GlobalIndirectTintColor, _CharacterRenderTimelineIndirectTintColor, _CharacterRenderTimelineIndirectLightWeight)

#if defined(CHARA_GLOBALS_USE_MONSTER) || defined(CHARA_GLOBALS_USE_GUN)
#undef _GlobalCharacterRenderLightDirection
#undef _GlobalCharacterRenderLightColor
#undef _GlobalCharacterRenderLightStrength
#undef _GlobalCharacterRenderLightToggle
#undef _GlobalCharacterRenderLightFollowCameraXZ
#undef _GlobalCharacterAdditionalLightsEnabled
#undef _GlobalCharacterAdditionalLightsDiffuseEnabled
#undef _GlobalCharacterAdditionalLightsSpecularEnabled
#undef _GlobalCharacterRenderOverrideSceneAmbient
#undef _GlobalIndirecIntensity
#undef _GlobalIndirectTintColor
#undef _GlobalCharacterRenderOutlineToggle
#undef _GlobalCharacterRenderRimLightToggle
#undef _GlobalCharacterRenderFinalColorGradientToggle
#undef _GlobalCharacterRenderFinalColorGradientParametersOverride
#undef _GlobalCharacterRenderFinalColorGradientColor
#undef _GlobalCharacterRenderFinalColorGradientMinY
#undef _GlobalCharacterRenderFinalColorGradientMaxY
#if defined(CHARA_GLOBALS_USE_GUN)
#define CHARA_GLOBALS_MAIN_LIGHT_DIRECTION _GlobalGunRenderLightDirection
#define CHARA_GLOBALS_MAIN_LIGHT_COLOR _GlobalGunRenderLightColor
#define CHARA_GLOBALS_MAIN_LIGHT_STRENGTH _GlobalGunRenderLightStrength
#define CHARA_GLOBALS_MAIN_LIGHT_TOGGLE _GlobalGunRenderLightToggle
#define CHARA_GLOBALS_MAIN_LIGHT_FOLLOW_CAMERA_XZ _GlobalGunRenderLightFollowCameraXZ
#define CHARA_GLOBALS_ADDITIONAL_LIGHTS_ENABLED _GlobalGunAdditionalLightsEnabled
#define CHARA_GLOBALS_ADDITIONAL_LIGHTS_DIFFUSE_ENABLED _GlobalGunAdditionalLightsDiffuseEnabled
#define CHARA_GLOBALS_ADDITIONAL_LIGHTS_SPECULAR_ENABLED _GlobalGunAdditionalLightsSpecularEnabled
#define CHARA_GLOBALS_OVERRIDE_SCENE_AMBIENT _GlobalGunRenderOverrideSceneAmbient
#define CHARA_GLOBALS_INDIRECT_INTENSITY _GlobalGunIndirectIntensity
#define CHARA_GLOBALS_INDIRECT_TINT_COLOR _GlobalGunIndirectTintColor
#define CHARA_GLOBALS_OUTLINE_TOGGLE _GlobalGunRenderOutlineToggle
#define CHARA_GLOBALS_RIM_TOGGLE _GlobalGunRenderRimLightToggle
#define CHARA_GLOBALS_GRADIENT_TOGGLE _GlobalGunRenderFinalColorGradientToggle
#define CHARA_GLOBALS_GRADIENT_OVERRIDE _GlobalGunRenderFinalColorGradientParametersOverride
#define CHARA_GLOBALS_GRADIENT_COLOR _GlobalGunRenderFinalColorGradientColor
#define CHARA_GLOBALS_GRADIENT_MIN_Y _GlobalGunRenderFinalColorGradientMinY
#define CHARA_GLOBALS_GRADIENT_MAX_Y _GlobalGunRenderFinalColorGradientMaxY
#else
#define CHARA_GLOBALS_MAIN_LIGHT_DIRECTION _GlobalMonsterRenderLightDirection
#define CHARA_GLOBALS_MAIN_LIGHT_COLOR _GlobalMonsterRenderLightColor
#define CHARA_GLOBALS_MAIN_LIGHT_STRENGTH _GlobalMonsterRenderLightStrength
#define CHARA_GLOBALS_MAIN_LIGHT_TOGGLE _GlobalMonsterRenderLightToggle
#define CHARA_GLOBALS_MAIN_LIGHT_FOLLOW_CAMERA_XZ _GlobalMonsterRenderLightFollowCameraXZ
#define CHARA_GLOBALS_ADDITIONAL_LIGHTS_ENABLED _GlobalMonsterAdditionalLightsEnabled
#define CHARA_GLOBALS_ADDITIONAL_LIGHTS_DIFFUSE_ENABLED _GlobalMonsterAdditionalLightsDiffuseEnabled
#define CHARA_GLOBALS_ADDITIONAL_LIGHTS_SPECULAR_ENABLED _GlobalMonsterAdditionalLightsSpecularEnabled
#define CHARA_GLOBALS_OVERRIDE_SCENE_AMBIENT _GlobalMonsterRenderOverrideSceneAmbient
#define CHARA_GLOBALS_INDIRECT_INTENSITY _GlobalMonsterIndirectIntensity
#define CHARA_GLOBALS_INDIRECT_TINT_COLOR _GlobalMonsterIndirectTintColor
#define CHARA_GLOBALS_OUTLINE_TOGGLE _GlobalMonsterRenderOutlineToggle
#define CHARA_GLOBALS_RIM_TOGGLE _GlobalMonsterRenderRimLightToggle
#define CHARA_GLOBALS_GRADIENT_TOGGLE _GlobalMonsterRenderFinalColorGradientToggle
#define CHARA_GLOBALS_GRADIENT_OVERRIDE _GlobalMonsterRenderFinalColorGradientParametersOverride
#define CHARA_GLOBALS_GRADIENT_COLOR _GlobalMonsterRenderFinalColorGradientColor
#define CHARA_GLOBALS_GRADIENT_MIN_Y _GlobalMonsterRenderFinalColorGradientMinY
#define CHARA_GLOBALS_GRADIENT_MAX_Y _GlobalMonsterRenderFinalColorGradientMaxY
#endif
#define _GlobalCharacterRenderLightDirection CharaTimelineOverrideFloat3(CHARA_GLOBALS_MAIN_LIGHT_DIRECTION, _CharacterRenderTimelineMainLightDirection, _CharacterRenderTimelineMainLightWeight)
#define _GlobalCharacterRenderLightColor CharaTimelineOverrideFloat4(CHARA_GLOBALS_MAIN_LIGHT_COLOR, _CharacterRenderTimelineMainLightColor, _CharacterRenderTimelineMainLightWeight)
#define _GlobalCharacterRenderLightStrength CharaTimelineOverrideFloat(CHARA_GLOBALS_MAIN_LIGHT_STRENGTH, _CharacterRenderTimelineMainLightStrength, _CharacterRenderTimelineMainLightWeight)
#define _GlobalCharacterRenderLightToggle CharaTimelineOverrideFloat(CHARA_GLOBALS_MAIN_LIGHT_TOGGLE, _CharacterRenderTimelineMainLightToggle, _CharacterRenderTimelineMainLightWeight)
#define _GlobalCharacterRenderLightFollowCameraXZ CharaTimelineOverrideFloat(CHARA_GLOBALS_MAIN_LIGHT_FOLLOW_CAMERA_XZ, _CharacterRenderTimelineMainLightFollowCameraXZ, _CharacterRenderTimelineMainLightWeight)
#define _GlobalCharacterAdditionalLightsEnabled CharaTimelineOverrideFloat(CHARA_GLOBALS_ADDITIONAL_LIGHTS_ENABLED, _CharacterRenderTimelineAdditionalLightsEnabled, _CharacterRenderTimelineAdditionalLightsWeight)
#define _GlobalCharacterAdditionalLightsDiffuseEnabled CharaTimelineOverrideFloat(CHARA_GLOBALS_ADDITIONAL_LIGHTS_DIFFUSE_ENABLED, _CharacterRenderTimelineAdditionalLightsDiffuseEnabled, _CharacterRenderTimelineAdditionalLightsWeight)
#define _GlobalCharacterAdditionalLightsSpecularEnabled CharaTimelineOverrideFloat(CHARA_GLOBALS_ADDITIONAL_LIGHTS_SPECULAR_ENABLED, _CharacterRenderTimelineAdditionalLightsSpecularEnabled, _CharacterRenderTimelineAdditionalLightsWeight)
#define _GlobalCharacterRenderOverrideSceneAmbient CharaTimelineOverrideFloat(CHARA_GLOBALS_OVERRIDE_SCENE_AMBIENT, _CharacterRenderTimelineOverrideSceneAmbient, _CharacterRenderTimelineIndirectLightWeight)
#define _GlobalIndirecIntensity CharaTimelineOverrideFloat(CHARA_GLOBALS_INDIRECT_INTENSITY, _CharacterRenderTimelineIndirectIntensity, _CharacterRenderTimelineIndirectLightWeight)
#define _GlobalIndirectTintColor CharaTimelineOverrideFloat3(CHARA_GLOBALS_INDIRECT_TINT_COLOR, _CharacterRenderTimelineIndirectTintColor, _CharacterRenderTimelineIndirectLightWeight)
#define _GlobalCharacterRenderOutlineToggle CharaTimelineOverrideFloat(CHARA_GLOBALS_OUTLINE_TOGGLE, _CharacterRenderTimelineOutlineToggle, _CharacterRenderTimelineOutlineWeight)
#define _GlobalCharacterRenderRimLightToggle CharaTimelineOverrideFloat(CHARA_GLOBALS_RIM_TOGGLE, _CharacterRenderTimelineRimLightToggle, _CharacterRenderTimelineRimLightWeight)
#define _GlobalCharacterRenderFinalColorGradientToggle CharaTimelineOverrideFloat(CHARA_GLOBALS_GRADIENT_TOGGLE, _CharacterRenderTimelineFinalGradientToggle, _CharacterRenderTimelineFinalGradientWeight)
#define _GlobalCharacterRenderFinalColorGradientParametersOverride CharaTimelineOverrideFloat(CHARA_GLOBALS_GRADIENT_OVERRIDE, _CharacterRenderTimelineFinalGradientParametersOverride, _CharacterRenderTimelineFinalGradientWeight)
#define _GlobalCharacterRenderFinalColorGradientColor CharaTimelineOverrideFloat4(CHARA_GLOBALS_GRADIENT_COLOR, _CharacterRenderTimelineFinalGradientColor, _CharacterRenderTimelineFinalGradientWeight)
#define _GlobalCharacterRenderFinalColorGradientMinY CharaTimelineOverrideFloat(CHARA_GLOBALS_GRADIENT_MIN_Y, _CharacterRenderTimelineFinalGradientMinY, _CharacterRenderTimelineFinalGradientWeight)
#define _GlobalCharacterRenderFinalColorGradientMaxY CharaTimelineOverrideFloat(CHARA_GLOBALS_GRADIENT_MAX_Y, _CharacterRenderTimelineFinalGradientMaxY, _CharacterRenderTimelineFinalGradientWeight)
#endif

#endif
